# -*- coding: utf-8 -*-
"""GuessTheNumber.ipynb

Automatically generated by Colaboratory.


"""

"""
Sayı tahmin oyunu
"""
import random
random = random.randint(0,100)
count = 0
while True:
  count +=1
  print("0 ile 100 arası bir sayı giriniz oyundan çıkmak için 'e' tuşuna basınız")
  sayi = input()

  if sayi.lower() == "e":
    print("Oyundan çıkış yaptınız")
    break

#isdigit tamamen sayılardan oluşuyor mu kontrol ediyor
  if not sayi.isdigit() or not  (0 <= int(sayi) <= 100):
    print("Lütfen 0-100 arasında bir sayı giriniz")
    continue
  sayi = int(sayi)
  if sayi == random:
    print("Tebrikler,doğru sayıya ulaştınız")
    print(str(count),"kere sayı tahmin ettiniz")
    break
  elif sayi < random:
    print("Sayınız küçük")
  else:
    print("Sayınız büyük")
